name: Deploy to DigitalOcean

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME }}
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image (optional)
        if: ${{ secrets.DOCKERHUB_USERNAME }}
        run: docker push <your_username>/my-nextjs-app:latest

      - name: SSH to DigitalOcean Droplet
        uses: digitalocean/action-do-ssh@v2
        with:
          private_key: ${{ secrets.DO_PRIVATE_KEY }}
          host: ${{ secrets.DO_HOST }}
          user: ${{ secrets.DO_USER }}

      - name: Pull latest Docker images
        run: docker-compose pull

      - name: Run the application
        run: docker-compose up -d
